name: Deploy app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build
      run: docker build -t marcelomg123/react-test -f ./client/Dockerfile.dev ./client
    - name: Test
      run: docker run -e CI=true marcelomg123/react-test npm test

    - name: Build Docker images (client)
      run: docker build -t marcelomg123/multi-client ./client
    - name: Build Docker images (nginx)
      run: docker build -t marcelomg123/multi-nginx ./nginx
    - name: Build Docker images (server)
      run: docker build -t marcelomg123/multi-server ./server
    - name: Build Docker images (worker)
      run: docker build -t marcelomg123/multi-worker ./worker

    - name: Push Docker images (client)
      run: docker push marcelomg123/multi-client
    - name: Push Docker images (nginx)
      run: docker push marcelomg123/multi-nginx
    - name: Push Docker images (server)
      run: docker push marcelomg123/multi-server
    - name: Push Docker images (worker)
      run: docker push marcelomg123/multi-worker

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: multi-docker
        environment_name: Multidocker-env
        existing_bucket_name: elasticbeanstalk-us-west-2-191514599439
        region: us-west-2
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip